
# This requirements file lists all third-party dependencies for this project.
#
# Run 'conda env create -f environment.yml' in a new conda environment.

name: varalign-env-py3
dependencies:
- python=3
- pip
- biopython
- matplotlib>=2.0.2,<=2.1.1
- numpy
- pandas==0.20.3
- pysam
- requests
- requests-cache
- scipy
- seaborn
- scikit-learn
- tqdm
- pyvcf
- pip:
  - proteofav
#  - prointvar-core
